### create
POST http://localhost:8080/article/moderator
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4OTg5NTgsImVtYWlsIjoiUk9OQUxETzFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA5Njk4OTU4LCJpc3MiOiJLdW5VelRlc3QifQ.kZ8HFFK8vKFLrXiKVfss1bmmza3BVop7qvhGOGKh-2MEyB-0w89Tw_ZMgIQuEFKGxX6SILfujDtdGmD6F7dPvA
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4OTM4MTQsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA5NjkzODE0LCJpc3MiOiJLdW5VelRlc3QifQ.x9c3ztXJMuTjbpcFSlXIPtAIKaCg7foPfIX00C-PosozQrVTCMoGil6gA5RWcB-F0pnw3pBLjT9oYl1TCZCT2A

{
  "titleUz": "World",
  "descriptionUz": "World",
  "contentUz": "World",
  "categoryId": 1,
  "regionId": 2,
  "articleType": [2],
  "photoId": "d1d0d620-e6eb-4a8f-9913-981bd526da33",
  "tagName": [3]
}

### update by moderator
PUT http://localhost:8080/article/moderator/02505de7-6ace-453b-b66e-c19d783d3019
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4OTg5NTgsImVtYWlsIjoiUk9OQUxETzFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA5Njk4OTU4LCJpc3MiOiJLdW5VelRlc3QifQ.kZ8HFFK8vKFLrXiKVfss1bmmza3BVop7qvhGOGKh-2MEyB-0w89Tw_ZMgIQuEFKGxX6SILfujDtdGmD6F7dPvA

{
  "title": "World",
  "description": "World",
  "content": "World",
  "categoryId": 1,
  "regionId": 1,
  "articleType": [2,3],
  "viewCount": 15 ,
  "imgId": "d1d0d620-e6eb-4a8f-9913-981bd526da33"
}


### delete by moderator
DELETE http://localhost:8080/article/moderator/e0c4afa1-6344-423d-b73a-4629cfe9b1ae
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4OTg5NTgsImVtYWlsIjoiUk9OQUxETzFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA5Njk4OTU4LCJpc3MiOiJLdW5VelRlc3QifQ.kZ8HFFK8vKFLrXiKVfss1bmmza3BVop7qvhGOGKh-2MEyB-0w89Tw_ZMgIQuEFKGxX6SILfujDtdGmD6F7dPvA

### change status by id by Publisher
PUT http://localhost:8080/article/moderator/changeStatus?id=c28a14ed-e3cf-493c-aaf4-93171f3a3b9c&status=PUBLISHED
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4OTg5NTgsImVtYWlsIjoiUk9OQUxETzFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA5Njk4OTU4LCJpc3MiOiJLdW5VelRlc3QifQ.kZ8HFFK8vKFLrXiKVfss1bmmza3BVop7qvhGOGKh-2MEyB-0w89Tw_ZMgIQuEFKGxX6SILfujDtdGmD6F7dPvA

### last 5 by type
GET http://localhost:8080/article/last5ByType?typeId=2

###
GET http://localhost:8080/article/last3ByType?typeId=2

### last 8
GET http://localhost:8080/article/last8ByType
Content-Type: application/json

{
  "articleIdList": ["548e99e9-b42b-4295-98fb-fcce733e7a47","208f290e-21e9-42a7-88bc-edf65dd009f5","bf52e409-bcff-46f2-b708-55ceb7b7fda8"]
}

### last 4 by type and article ids
GET http://localhost:8080/article/last4ByType?typeId=2&articleId=fdc0e0cf-71ac-4548-b223-3c43a4f00a8d


### most read 4 article
GET http://localhost:8080/article/mostRead4Article

### Last 4 article by tag
GET http://localhost:8080/article/last4ByTagId?tagId=1


### last 5 by typeID and RegionID
GET http://localhost:8080/article/getByTypeIdAndRegionId?typeId=2&regionId=1


### pagination by region id
GET http://localhost:8080/article/paginationByRegionId?page=1&size=12&regionId=2

### last 5 by category id
GET http://localhost:8080/article/last5ByCategoryId?categoryID=1

### last 5 by category id
GET http://localhost:8080/article/paginationByCategoryId?page=1&size=1&categoryId=2

### get by lang
GET http://localhost:8080/article/byLang?language=uz&articleId=c25e8c27-059f-4adb-b15f-d183ead14a66









