### init admin
GET http://localhost:8081/init/admin

### create profile by admin
POST http://localhost:8081/profile
Content-Type: application/json
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYzNjAwMDUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY0NDY0MDUsImlzcyI6Ikt1blV6VGVzdCJ9.qOuAn5LRAItUKngoYX11iuB-kGikna_j6zitHrntPQxXdBQyx7vbrH2v7NlVSaEUj-I48iysxu_jt2EUgtpYIg

{
  "name": "Messi",
  "surname": "Allayorov",
  "email": "messi@gmail.com",
  "password": "123",
  "phone": "123",
  "role":"MODERATOR"
}
### update only by admin
PUT http://localhost:8081/profile/4
Content-Type: application/json
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYzNjAwMDUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY0NDY0MDUsImlzcyI6Ikt1blV6VGVzdCJ9.qOuAn5LRAItUKngoYX11iuB-kGikna_j6zitHrntPQxXdBQyx7vbrH2v7NlVSaEUj-I48iysxu_jt2EUgtpYIg

{
"name": "Shakhzod",
"surname": "Allayarov",
"email": "shahzod23@gmail.com",
"password": "777",
"phone": "123",
"role":"PUBLISHER"
}

### pagination
GET http://localhost:8081/profile/pagination?size=3&page=1
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYzNjAwMDUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY0NDY0MDUsImlzcyI6Ikt1blV6VGVzdCJ9.qOuAn5LRAItUKngoYX11iuB-kGikna_j6zitHrntPQxXdBQyx7vbrH2v7NlVSaEUj-I48iysxu_jt2EUgtpYIg

### delete by admin
DELETE http://localhost:8081/profile/2
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYzNjAwMDUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY0NDY0MDUsImlzcyI6Ikt1blV6VGVzdCJ9.qOuAn5LRAItUKngoYX11iuB-kGikna_j6zitHrntPQxXdBQyx7vbrH2v7NlVSaEUj-I48iysxu_jt2EUgtpYIg

### update detail (ANY)
PUT http://localhost:8081/profile/update/2
Content-Type:application/json
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYzNzcyMDAsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA2NDYzNjAwLCJpc3MiOiJLdW5VelRlc3QifQ.dLErzCpkJcRTwvmC1KEMLsgG1HzMRNtpRatBS7EJ7ohjjAW5AFQZ6yrXSdvCa8cjh3Z10n8vpwfz9u0MmfcTlA

{
  "name": "Ronaldobek",
  "surname": "Cris",
  "email": "roanldo@gmail.com",
  "phone": "777",
  "password": "777"
}

### filter by Admin
GET http://localhost:8081/profile/filter
Content-Type: application/json
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYzNjAwMDUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY0NDY0MDUsImlzcyI6Ikt1blV6VGVzdCJ9.qOuAn5LRAItUKngoYX11iuB-kGikna_j6zitHrntPQxXdBQyx7vbrH2v7NlVSaEUj-I48iysxu_jt2EUgtpYIg


{
  "fromDate": "2024-01-26"
}