### init admin
GET http://localhost:8081/init/admin

### create profile by admin
POST http://localhost:8081/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY4NTg1MTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY5NDQ5MTEsImlzcyI6Ikt1blV6VGVzdCJ9.c07EScAKFag-Mu25tKFdc-6oOarpepjg9x0SuzSwOrhRlbLEu4MTiJG6DSeDTGyJ8pjjk5JULD6WneY1QmXlTQ

{
  "name": "Messi",
  "surname": "Allayorov",
  "email": "messi@gmail.com",
  "password": "123",
  "phone": "123",
  "role":"MODERATOR"
}

### get by id
GET http://localhost:8081/profile/adm/2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTI4NTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTkyNTcsImlzcyI6Ikt1blV6VGVzdCJ9.7SJOl_Kc0UWoRcVwG5d97CYAliW8cxzSemRDHo3UzIs4OPmBlJcVDL_3FJh8cgCFUY9xFQFrognjwe9Daz8HBA

### update only by admin
PUT http://localhost:8081/profile/adm/2
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTI4NTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTkyNTcsImlzcyI6Ikt1blV6VGVzdCJ9.7SJOl_Kc0UWoRcVwG5d97CYAliW8cxzSemRDHo3UzIs4OPmBlJcVDL_3FJh8cgCFUY9xFQFrognjwe9Daz8HBA

{
"name": "Shakhzod",
"surname": "Allayarov",
"email": "shahzod23@gmail.com",
"password": "777",
"phone": "123",
"role":"PUBLISHER"
}

### pagination
GET http://localhost:8081/profile/adm/pagination?size=3&page=1
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTI4NTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTkyNTcsImlzcyI6Ikt1blV6VGVzdCJ9.7SJOl_Kc0UWoRcVwG5d97CYAliW8cxzSemRDHo3UzIs4OPmBlJcVDL_3FJh8cgCFUY9xFQFrognjwe9Daz8HBA
### delete by admin
DELETE http://localhost:8081/profile/2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTI4NTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTkyNTcsImlzcyI6Ikt1blV6VGVzdCJ9.7SJOl_Kc0UWoRcVwG5d97CYAliW8cxzSemRDHo3UzIs4OPmBlJcVDL_3FJh8cgCFUY9xFQFrognjwe9Daz8HBA

### update detail (ANY)
PUT http://localhost:8081/profile/adm/update
Content-Type:application/json
Authorization:Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjcyMjYsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA2NTEzNjI2LCJpc3MiOiJLdW5VelRlc3QifQ.vuW9WBR73ayvQLFFzJiLdEvKesLoPzUJXOOHITGYIPF3uBwvHjxjwm5dLwcELiKKVVoer7wXBuPIPd7rfoGKFA

{
  "name": "Ronaldobek",
  "surname": "Cris",
  "email": "roanldo@gmail.com",
  "phone": "777",
  "password": "777"
}

### filter by Admin
GET http://localhost:8081/profile/filter
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTI4NTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTkyNTcsImlzcyI6Ikt1blV6VGVzdCJ9.7SJOl_Kc0UWoRcVwG5d97CYAliW8cxzSemRDHo3UzIs4OPmBlJcVDL_3FJh8cgCFUY9xFQFrognjwe9Daz8HBA


{
  "fromDate": "2024-01-26"
}